"""Acceptance coverage for the autonomous runtime seam.

These tests start at ``SocialAgentRuntime``.  Calling ``Session.episode``
directly would prove the old one-shot runner again and miss the Attention
Loop that this effort exists to add.
"""

from __future__ import annotations

import json

from misty_agent.agent.journal import EpisodeFinished, StopRequested
from misty_agent.agent.react import Decision
from misty_agent.app import simulated_session
from misty_agent.config import Settings
from misty_agent.demo import answer
from misty_agent.fakes import FakeClock
from misty_agent.runtime import (
    RuntimeState,
    ScenarioInputAdapter,
    SocialAgentRuntime,
    TimedText,
)
from misty_agent.scenarios import EXPLICIT_TEXT_REQUEST, ScenarioModel


class ScriptedModel:
    """The hosted-model boundary, replaced by two deterministic decisions."""

    def __init__(self) -> None:
        self._decisions = [
            Decision(
                tool="speak",
                args={"text": "Hello — what can I do for you?"},
                tokens_in=20,
                tokens_out=8,
            ),
            Decision(tool="done", args={}, tokens_in=34, tokens_out=1),
        ]

    def decide(self, working_context, tools):
        return self._decisions.pop(0)


def test_a_timed_explicit_request_runs_from_attention_to_a_simulated_effect():
    """Ticket 01's tracer bullet crosses the new highest public seam."""
    clock = FakeClock()
    source = ScenarioInputAdapter(
        clock,
        EXPLICIT_TEXT_REQUEST.inputs,
    )
    session = simulated_session(
        None,
        model=ScenarioModel(EXPLICIT_TEXT_REQUEST.decisions),
        clock=clock,
    )
    runtime = SocialAgentRuntime(source=source, session=session, clock=clock)

    result = runtime.run()

    assert result.ending == "input_exhausted"
    assert runtime.state is RuntimeState.STOPPED
    assert [record.type for record in result.records] == [
        "attention_started",
        "cue_detected",
        "episode_opened",
        "episode_completed",
        "attention_stopped",
    ]
    assert result.records[1].cue_kind == "explicit_request"
    assert result.records[1].t == EXPLICIT_TEXT_REQUEST.inputs[0].at_s
    assert len(result.episodes) == 1
    episode = result.episodes[0]
    assert episode.outcome.outcome == "done"
    assert isinstance(episode.journal.records[-1], EpisodeFinished)
    assert "tts/speak" in session.robot.endpoints


def test_the_demo_replays_a_text_case_that_crossed_the_runtime_seam():
    """The built-in tracer is generated by the runtime, not a direct Episode."""
    reply = answer("GET", "/examples/runtime_explicit_text_request")

    assert reply.status == 200
    payload = json.loads(reply.body)
    assert payload["example"]["name"] == EXPLICIT_TEXT_REQUEST.name
    assert payload["runtime"]["records"][1]["text"] == (
        EXPLICIT_TEXT_REQUEST.inputs[0].text
    )
    assert [record["type"] for record in payload["runtime"]["records"]] == [
        "attention_started",
        "cue_detected",
        "episode_opened",
        "episode_completed",
        "attention_stopped",
    ]
    assert payload["runtime"]["episodes"][0]["cue_kind"] == "explicit_request"
    assert payload["storyboard"]["outcome"] == "done"
    assert payload["storyboard"]["moments"][-1]["kind"] == "episode_finished"


def test_text_entered_in_the_demo_also_crosses_the_runtime(monkeypatch):
    """The old one-shot Episode is no longer the Demo's product boundary."""
    monkeypatch.setenv("OPENAI_API_KEY", "sk-not-a-real-key")
    monkeypatch.setattr(
        "misty_agent.demo.OpenAIModel", lambda: ScriptedModel()
    )
    body = json.dumps({"trigger": "speech", "said": "Misty, hello"}).encode()

    payload = json.loads(answer("POST", "/run", body).body)

    assert payload["runtime"]["records"][1]["type"] == "cue_detected"
    assert payload["runtime"]["episodes"][0]["cue_kind"] == "explicit_request"
    assert payload["storyboard"]["outcome"] == "done"


def test_an_input_failure_still_stops_the_runtime_with_a_bounded_result():
    """A broken adapter must not strand the Attention Loop in ``running``."""

    class BrokenInput:
        def __init__(self) -> None:
            self.stopped = False

        def start(self) -> None:
            pass

        def read(self):
            raise RuntimeError("scenario input failed")

        def stop(self) -> None:
            self.stopped = True

    clock = FakeClock()
    source = BrokenInput()
    session = simulated_session(None, model=ScriptedModel(), clock=clock)
    runtime = SocialAgentRuntime(source=source, session=session, clock=clock)

    result = runtime.run()

    assert result.ending == "runtime_error"
    assert [record.type for record in result.records] == [
        "attention_started",
        "runtime_failed",
        "attention_stopped",
    ]
    assert source.stopped
    assert runtime.state is RuntimeState.STOPPED


def test_shutdown_aborts_the_active_episode_and_returns_a_bounded_result():
    """Runtime shutdown may interrupt an Episode but never strand one."""

    class StopsDuringDecision:
        runtime = None

        def decide(self, working_context, tools):
            self.runtime.stop()
            return Decision(
                tool="speak",
                args={"text": "this must not be spoken"},
                tokens_in=10,
                tokens_out=2,
            )

    clock = FakeClock()
    model = StopsDuringDecision()
    session = simulated_session(None, model=model, clock=clock)
    runtime = SocialAgentRuntime(
        source=ScenarioInputAdapter(
            clock, [TimedText(at_s=0.0, text="Misty, hello")]
        ),
        session=session,
        clock=clock,
    )
    model.runtime = runtime

    result = runtime.run()

    assert result.ending == "shutdown"
    assert result.episodes[0].outcome.outcome == "aborted"
    stops = [
        record
        for record in result.episodes[0].journal.records
        if isinstance(record, StopRequested)
    ]
    assert [stop.source for stop in stops] == ["runtime_shutdown"]
    assert "tts/speak" not in session.robot.endpoints


def test_the_existing_turn_cap_remains_the_runtime_episode_bound():
    """The autonomous shell does not weaken the inner ReAct bound."""

    class KeepsTalking:
        def decide(self, working_context, tools):
            return Decision(
                tool="speak",
                args={"text": "still going"},
                tokens_in=10,
                tokens_out=2,
            )

    clock = FakeClock()
    session = simulated_session(None, model=KeepsTalking(), clock=clock)
    session.config = Settings(max_turns_per_episode=2)
    runtime = SocialAgentRuntime(
        source=ScenarioInputAdapter(
            clock, [TimedText(at_s=0.0, text="Misty, hello")]
        ),
        session=session,
        clock=clock,
    )

    result = runtime.run()

    episode = result.episodes[0]
    assert episode.outcome.outcome == "turn_limit"
    assert episode.outcome.turns == 2
    assert session.robot.endpoints.count("tts/speak") == 2


def test_an_episode_error_closes_both_episode_and_runtime():
    """Dependency failures remain typed endings at the highest seam."""

    class ModelFails:
        def decide(self, working_context, tools):
            raise RuntimeError("model connection failed")

    clock = FakeClock()
    session = simulated_session(None, model=ModelFails(), clock=clock)
    runtime = SocialAgentRuntime(
        source=ScenarioInputAdapter(
            clock, [TimedText(at_s=0.0, text="Misty, hello")]
        ),
        session=session,
        clock=clock,
    )

    result = runtime.run()

    assert result.ending == "episode_error"
    assert result.episodes[0].outcome.outcome == "error"
    assert result.episodes[0].journal.records[-1].outcome == "error"
    assert result.records[-1].type == "attention_stopped"


def test_two_requests_never_own_the_robot_at_the_same_time():
    """A later cue opens only after the earlier Episode has completed."""

    class StopsEachEpisode:
        def decide(self, working_context, tools):
            return Decision(tool="done", args={}, tokens_in=8, tokens_out=1)

    clock = FakeClock()
    session = simulated_session(None, model=StopsEachEpisode(), clock=clock)
    runtime = SocialAgentRuntime(
        source=ScenarioInputAdapter(
            clock,
            [
                TimedText(at_s=0.0, text="first request"),
                TimedText(at_s=0.1, text="second request"),
            ],
        ),
        session=session,
        clock=clock,
    )

    result = runtime.run()

    boundaries = [
        record.type
        for record in result.records
        if record.type in {"episode_opened", "episode_completed"}
    ]
    assert boundaries == [
        "episode_opened",
        "episode_completed",
        "episode_opened",
        "episode_completed",
    ]
    assert len(result.episodes) == 2
